#Generated by Fabric Compiler ( version 2019.1-patch2 <build 42169> ) at Fri Nov 13 09:28:33 2020

set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_design "E:/Image_Rotat_master/Image/source/div.v"
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
remove_design -force -verilog "E:/Image_Rotat_master/Image/source/display_module/char2_array_decode.v"
remove_design -force -verilog "E:/Image_Rotat_master/Image/source/coor_trans/hdl/coor_trans.v"
remove_design -force -verilog "E:/Image_Rotat_master/Image/source/coor_trans/hdl/coor_trans_forward.v"
remove_design -force -verilog "E:/Image_Rotat_master/Image/source/coor_trans/hdl/coor_trans_reverse.v"
remove_design -force -verilog "E:/Image_Rotat_master/Image/source/display_module/char_array_decode.v"
remove_design -force -verilog "E:/Image_Rotat_master/Image/source/coor_trans/hdl/cos_table.v"
remove_design -force -verilog "E:/Image_Rotat_master/Image/source/coor_trans/hdl/sin_table.v"
